### PR TITLE
Remove execution bit of composer.json

### PR DESCRIPTION
**Pull request by szepeviktor**
@johnpbloch Please consider merging it.

### CODE REVIEW

**Comment by johnpbloch** [comment]
One of the larger problems with Windows as a primary development machine... 🙈

**Comment by johnpbloch** [comment]
This change will definitely go in; I'm just thinking of what the best way to do it will be.

**Comment by johnpbloch** [comment]
@szepeviktor I think the best way to implement this change is to do so in the automated build repository. If you could please open a pull request adding `chmod 644 ./composer.json` here: https://github.com/johnpbloch/build-wp/blob/master/build-wp.sh#L107 I'll merge it in (and that way you'll get the commit in git history). That change will trickle into trunk today and will make it into all the branches and all future tags on next release.

I'm going to go ahead and close this PR, since even if I did merge it, the executable bit would be back the next time the build process runs again.

**Comment by szepeviktor** [comment]
Thank you.

**Pull request closed without merging**
